### ISSUE TITLE
Links to Hands-On-Labs are not working

### ISSUE THREAD

**Issue by striple66** [Microsoft/MCW-Big-data-and-visualization#19]
Hi there, the links to both hands-on-labs (step-by-step and unguided) are not working "Page 404 - not found". Can you please fix this?

Thanks

**Comment by DawnmarieDesJardins** [comment]
Hello!
(Added Joel for visibility)
Thanks for creating this issues.  I've tested the lab links and they are working for me.  Can you try again please?  If you're still getting a 404 error, copy/paste the link you're using maybe?

**Comment by striple66** [comment]
Hi there, the links from the starting page HOL (https://github.com/Microsoft/MCW-Big-data-and-visualization/tree/master/Hands-on%20lab) at the bottom of the page "Hands-On-Lab" do not work. 


https://github.com/Microsoft/MCW-Big-data-and-visualization/blob/master/Hands-on%20lab/HOL-step-by-step-Big-data-and-visualization.md

and

https://github.com/Microsoft/MCW-Big-data-and-visualization/blob/master/Hands-on%20lab/HOL-unguided-Big-data-and-visualization.md

The links from the resources on top of the page work just fine. 

**But I found another issue:** in the "Before the HOL - Big data and visualization.md" is a section "Task 9: Create an Azure Databricks cluster". In this section we are asked to create a Databricks cluster of version "Databricks Runtime Version: 3.4 (includes Apache Spark 2.2.0, Scala 2.11)".  Note: Select 3.4 and not a newer version such as 4.1. This is so that the exported machine learning model will be compatible with the version of Spark currently installed on DSVM.

However, in Databricks Workspace Cluster Management, we can only create a Databricks Runtime "3.5 LTS (includes Apache Spark 2.2.1, Scala 2.11)". Will the labs work even with 3.5 runtime of Databricks?

Thanks and best regards

Ralf

**Comment by joelhulen** [comment]
These are all addressed in the changes within the `august-2018-testfix` branch. Waiting for branch to be merged to master.

**Comment by DawnmarieDesJardins** [comment]
Closing issue, addressed in August 2018 test/fix, now merged to master.
