### ISSUE TITLE
HOL unguided - Big data and visualization.md Cmd 32 - wrong spark function name

### ISSUE THREAD

**Issue by striple66** [Microsoft/MCW-Big-data-and-visualization#23]
Hi there,
in HOL unguided - Big data and visualization.md in cell 32 there is an instruction saying that we should use the spark command `SaveTableAs().` This function is not existing. Instead it should be `SaveAsTable()`.

`dfFlightDelays_Clean.write.saveAsTable("flight_delays_clean")`

**Comment by mrfalafel** [comment]
Fixed the type in the "01 Prepare flight Data Complete.dbc" from saveTableAs to saveAsTable

**Comment by DawnmarieDesJardins** [comment]
Closing issue, addressed in August 2018 test/fix, now merged to master.
