### ISSUE TITLE
broken links in CONTRIBUTING.md

### ISSUE THREAD

**Issue by anneneo** [Microsoft/MCW-Big-data-and-visualization#28]
hi,

  there are some broken links in CONTRIBUTING.md file. Below are 3 broken links which require fixing:

- Before you create a new issue, please do a search in **_open issues_** to see if the issue or feature request has already been filed.
- Be sure to scan through the **_most popular_** feature requests.
- If you are interested in writing code to fix issues, please see **_How to Contribute_** in the wiki.

**Comment by DawnmarieDesJardins** [comment]
Merged through pull request, closing issue.
