### ISSUE TITLE
"CredSSP encryption oracle remediation" error when RDP to a Windows VM in Azure

### ISSUE THREAD

**Issue by juliusc88** [Microsoft/MCW-Big-data-and-visualization#3]
Followed the Lab steps to created the DSVM and encountered the below error when RDP to the DSVM.

"CredSSP encryption oracle remediation" error when RDP to a Windows VM in Azure

The below KB describes the issue and workaround.
https://support.microsoft.com/en-us/help/4295591/credssp-encryption-oracle-remediation-error-when-to-rdp-to-azure-vm

I had followed the workaround options and still unable to RDP the DSVM.

We may need to address this issue prior to the workshop or will not able to proceed with the lab.

**Comment by joelhulen** [comment]
@juliusc88, can you please try installing the Microsoft Remote Desktop app from the Microsoft Store? The CredSSP appears to only affect the Remote Desktop Connection client installed with Windows. Here's the link: https://www.microsoft.com/store/productId/9WZDNCRFJ3PS

If that works for you, then I'll add it into the setup instructions.

**Comment by juliusc88** [comment]
@joelhulen Microsoft Remote Desktop app works for me!

**Comment by joelhulen** [comment]
I've updated the setup instructions accordingly.
