### ISSUE TITLE
Machine learning experimentation/ Model management ( Retiring)

### ISSUE THREAD

**Issue by Abhishekpathania01** [Microsoft/MCW-Big-data-and-visualization#30]
In Before Hands on lab Step 8. Creating Azure Resources **Machine Learning Experimentation** and **Machine Learning Model Management**
But the **current status** of these resources in Azure portal is **Retiring**

![image](https://user-images.githubusercontent.com/38715522/47607500-6b6e0500-da3e-11e8-8252-4e9a932b7982.png)

**Comment by Abhishekpathania01** [comment]
![image](https://user-images.githubusercontent.com/38715522/47607576-77a69200-da3f-11e8-93a4-e9d36559b6e5.png)

**Comment by lastcoolnameleft** [comment]
I'm encountering this issue too.  Is there a recommended resource to use instead?

**Comment by mrfalafel** [comment]
This has been resolved for the November 2018 update.  Thanks
