### ISSUE TITLE
Content update scheduled

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Big-data-and-visualization#32]
This workshop is scheduled for an update. Please review the contents of this repo and comment on this issue with suggested updates. All suggestions must be added to this issue by EOD 11/9/18.

**Comment by oedenfield** [comment]
Hi - Contents on the Step-By-Step instructions seem to be out of order in my opinion.  Exercise 1 starts with building a machine learning model - instead of starting with the data.  I understand the **Before the HOL** document details steps that need to be taken to set everything up (including downloading the data) but I think it would be better to have people start with understanding the source data, exploring it with something like ML Workbench or even Azure Databricks.  I would suggest that in most cases customers have to start with a good understanding of their data before they can implement a classification experient.  Some customers I've worked with know _that they collect data about_ a particular business process or problem but they often don't know the characteristics, the shape or nature of that data.  This may be simple or pedantic but I think it's important.

**Comment by oedenfield** [comment]
Additionally, I think it would flow better if we started with getting the data into Azure - vs. starting with building a model in Exercise 1.  For example, Exercise 1 shows uploading data files using Azure Databricks - but then in subsequent exercises we're loading data into Azure with Azure Data Factory.  In fact the whole solution architecture diagram shows loading data with ADF.  So why not start with pulling the data from source using ADF (via REST API or some other API, so the data doesn't even have to be downloaded to a local machine) and then subsequent exercises would interact with the data in Blob Store.  Another option would be starting with ingesting the data into a Storage Account with Data Factory?

**Comment by DawnmarieDesJardins** [comment]
Comments from Anagha Khanolkar:

Did a quick browse and here are some things I wanted to share-
1.	 Azure ML workbench (desktop app) is targeted to be retired/deprecated.  Consider replacing the workbench with supported alternatives.  @Erik Zwiefel, can perhaps chime in on alternatives.  
2.	Can we add some messaging around the Power BI visualization.  Specifically - although PowerBI has a Spark direct query connector, in true big data scenarios, consider summarizing data targeted for visualization and piping to a reporting data mart (RDBMS) and visualizing off of.  I am yet to encounter a customer who needed to run PowerBI against the entire (big) dataset - I would question why.  Its usually - a small dataset, and usually batch.  For near-real-time, we should consider streaming and pushing to PowerBI, instead of pulling into PowerBI.
3.	Can we reference which version of Azure Data Factory for clarity?
4.	Is there going to be an architectural considerations section that rationalizes the architecture?  This would be helpful to lay out options and then why we went with the solution we did.  Apologies if this already exists and I missed it. My comment #2 is something that would go under architectural considerations. 
Best regards,
Anagha Khanolkar

**Comment by DawnmarieDesJardins** [comment]
Comments from Craig Rodger:

We ran this workshop a couple of weeks ago in Sydney so this feedback comes from that experience rather than going through the material with a fine tooth comb again. It would simply take too long.

1. The Big Data & Visualisation workshop is too long for a single day. It also lands up being click, run, read, click, run, read. The fastest members in the group got as far as the model deployment being complete. They never even got to the PowerBI or application deployment part
2. We did not use the whiteboard session at all. It takes quite good knowledge of the Azure components to be able to do it well. I was going to change that to a slightly different approach but in the interest of time just talked the group through the proposed solution architecture. It acted as a good reference point for the HOL component.
3. The workshop still refers to and uses ML Workbench. There are notices about it being deprecated which leads to a lot of questions about why it is being used. We managed to circumvent this but it does derail the process
4. While the Experimentation and model management services are critical for production purposes they demo very badly. I had two comments from attendees saying “so the highest opportunity for error is in this part” being the CLI command stretch. Very few managed to finish this section. The rest f the audience get an impression that that part is a little ‘flaky’ which is probably not fair and may leave a bad impression. It just does not ‘demo’ well.
5. There is little genuine problem solving in the HOL flow. Most problem solving seems to occur when the deployment fails (it always does for somebody in the group).
6. The app deployment is interesting, and may be necessary to show the web service in use. I would suggest we find a  simpler way to illustrate this and avoid the app deployment part. Most attendees to our workshop were more interested in the data pipeline and engineering rather than app integration. It is important but maybe not in a workshop context.

For future development of the workshop some ideas below. The workshop was overall very well received despite what look like a long list of problems above. I think we had a good group and we managed to execute it pretty well.

I would prefer to see 
1. More time spent in Databricks solving some more realistic problems. By this I mean not simple run the notebook, but maybe more cells with requirements for the users to complete.
2. Skip model deployment or make that more hidden. We could demonstrate calling a remote model without having to go through the pain of CLI deploying it.
3. Spend more on PowerBI, the session is called Big Data & Visulisation.
4. The whiteboard session with an informed group works okay. With a new group who don’t know much about all of MS Azure offerings it is next to impossible to get them to engineer a design when they don’t know what each thing does. This can however be used in a different way
Craig Rodger
Technology Solutions Professional GBB Australia & NZ

**Comment by DawnmarieDesJardins** [comment]
Comments from Alexander Zeltov (combination of multiple emails):

The one big request, is to switch the BigTravel Web App to VS Code and use Dot Net Core. This was a huge problem for folks running Macs , when I gave that workshop folks were very frustrated. We need to stop assuming everyone is running windows. VS Code is much easier for folks to install and dot net core is cross platform compatible.

Will continue reviewing the material, but I thinks this is “must” before we roll out the new version.

@Erik Zwiefel tagging Erik as I know he will have similar input, but will probably ask for a more OSS web app (python or other equivalent).

+1 On AML Workbench is retired. Needs to be pulled out of the lab.

We should include an explanation section for why we are doing some development in jupyter and than doing the batchscoring in Azure Databricks.  I personally think we should do the whole thing on ADB but that’s a separate conversation. Users will be confused on why we are doing some development in Jupyter and than using ADB.  Considering ADB can use the AML SDK natively now to do model management. 

I like the idea of making the webapp optional. And have the instructor demo the final product. This will simplify the students development stack and address the dotnet concerns.

Alex.

**Comment by DawnmarieDesJardins** [comment]
Comments from Anagha Khanolkar (combination of multiple emails):

1.	 Since Azure ML workbench is descoped, and we are doing parts in Databricks, why not do training and testing of the model in Spark on Databricks, and  batch scoring, and showcase AML for operationalizing model as REST service.
2.	In my opinion, de-scope the web app component.  In reality, data engineers don't get involved in web app dev, dont have the skills...I used to be a career big data engineer.  If you take the field roles, the ones who cover big data, dont cover web app dev.  Just knowing what the end to end picture looks like is great for the field - but we dont need to get into web app dev, you would lose some of the audience.  If there is extra time, consider adding more relevant content.

+1, there are several of us on Macs.
Most big data teams at our customers are as well.
Please switch to VS code. Thanks.

Best regards,
Anagha Khanolkar

**Comment by DawnmarieDesJardins** [comment]
Comments from Chad Gronbach:

The Azure ML command line sections will probably have to be re-written as well.  I don’t have time to really go through it, but this is all based on the old Azure ML preview.  The new stuff is very different.  I think it needs a complete overhaul.  

I’ve been traveling all week, so no time to look in detail, but I think there is a bit of work here.  Also, I agree with Alexander, I think we should focus on ADB and Azure ML working together.

Chad.

**Comment by DawnmarieDesJardins** [comment]
From Zoiner Tejada:

Adding Lino Tadros who can provide visibility into the plan, as I believe all of these concerns have already been addressed in the plan but want to enable him to participate in the conversation. 

(I've assigned this issue to Lino for further visibility.  Dawnmarie)

**Comment by mrfalafel** [comment]
Thank you! The update scheduled for November will eliminate the Lab VM all together.  Azure Databricks will be used instead of the Lab VM. The Web app will not be rewritten in DotNetCore because of time allowed to complete this update. All CLI command line procedures will be updated to the latest.
Thanks for all your great suggestions.

**Comment by jhasanjay** [comment]
I am struggling to create a new project using workbench. Is there any workaround or steps to help on this?

**Comment by DawnmarieDesJardins** [comment]
@jhasanjay 
Hello!  We've just completed an update on this workshop and several sections of the lab have been upgraded.  Please take a look and let us know if you are still having trouble.
Thanks for your input!
