### ISSUE TITLE
Creation of Lab VM is missing.

### ISSUE THREAD

**Issue by Abhishekpathania01** [Microsoft/MCW-Big-data-and-visualization#34]
We should create Lab VM in Before hands on Lab. Can someone look into this?

**Comment by mrfalafel** [comment]
Lab VM was removed in the latest update by design.  All labs are now conducted directly from the Databricks notebooks.

**Comment by Abhishekpathania01** [comment]
But, still I see In Exercise 2 Task 2: [Install and configure Azure Data Factory Integration Runtime on the Lab VM](https://github.com/Microsoft/MCW-Big-data-and-visualization/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Big%20data%20and%20visualization.md#task-2-install-and-configure-azure-data-factory-integration-runtime-on-the-lab-vm)
