### ISSUE TITLE
Use of Lab VM, as creation of Lab VM is missing but I see its in use In Hands on Lab Step by Steps.

### ISSUE THREAD

**Issue by Abhishekpathania01** [Microsoft/MCW-Big-data-and-visualization#35]
1. I had raised a issue earlier for Lab VM but author replied we have removed Lab VM in latest update, but I see use of Lab Vm is still there in [Exercise 2. Task 2](https://github.com/Microsoft/MCW-Big-data-and-visualization/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Big%20data%20and%20visualization.md#task-2-install-and-configure-azure-data-factory-integration-runtime-on-the-lab-vm)

* Here are some screenshots:
1.  Exercise 2 Task 2: Install and configure Azure Data Factory Integration Runtime on the **Lab VM**
![image](https://user-images.githubusercontent.com/38715522/51989695-9482b380-24cd-11e9-98eb-01da654ae42b.png)
2. Task 3: Configure Azure Data Factory Step 13.
![image](https://user-images.githubusercontent.com/38715522/51989705-99476780-24cd-11e9-843b-8abf048747da.png)

I am confused due to this, can anyone look into this ASAP, we have one workshop scheduled next week. Thanks

**Comment by mrfalafel** [comment]
Thanks a million Abhishek
I see it now.  I am so sorry, something went wrong during the checkin process.  There should be no mention of LabVM at all in this MCW.  I will revise the chapter ASAP to make sure that area of Data Factory does not contain any mention of the LabVM.
Thanks again for your help
-Lino

**Comment by mrfalafel** [comment]
Reference to LabVM corrected.
