### ISSUE TITLE
ML API Key

### ISSUE THREAD

**Issue by crrodger** [Microsoft/MCW-Big-data-and-visualization#37]
In Exercise 8, task 2 (deploying the application) the notes refer to "Finally, enter the ML API Primary key (we got that from Azure databricks Notebook #3, remember?) and Weather API information." ... I am struggling to find where this key actually came from?

This is in preparation for running a workshop next week. While not critical or a show stopper the revised content of the workshop makes it much more likely attendees will get all the way to the end and this point will be reached.

**Comment by mrfalafel** [comment]
When you deploy the application in Azure Databricks to create the Web Service (a new feature of Azure Machine Learning) the created Web Service automatically generates a Primary Key and a Secondary Key for the service to be used when called from outside clients for security reasons.  This feature has changed 3 times before the release of the final bits of Machine Learning Web Service deployments.
In this the Databricks notebook, I explain how to call the API to get the Primary Key to allow you to call the service from outside client applications.

**Comment by crrodger** [comment]
Hi,

Thanks for the reply.

I am somewhat familiar with the ml sdk for deploying models through the Model -> Image -> ACI -> AKS stages (previous project work on this) so I think I understand which part of the process you are referring to but for the life of me I cannot see in the Databricks notebook “03 Deploy as Web Service” any mention of the ML SDK Key retrieval (I cannot even find the works Primary” or “Key” in the notebook). The screenshot below is from the deployment and call part of the notebook and none of the configs contain an ML key.

[cid:image004.jpg@01D4BA2E.1814B820]



I also thought that one of the big difference between ACI and AKS was the ACI did not have authentication for the web service whereas AKS does (also from a previous project). I tested the webservice endpoint in this example using Postman without any authentication and it works so no key is required to call the service if deployed on ACI!?


[cid:image005.jpg@01D4BA2E.1814B820]

Am I looking in the wrong place?

Craig Rodger
Mobile: +61 406 176 831

**Comment by mrfalafel** [comment]
Hi 
Can you take a look at this blog I wrote a while back after the release of the product and let me know if that sheds some more light on the issue.
http://www.linotadros.com/blogpostdetails/lino-tadros-blogs/2018/11/19/getting-the-ml-api-key-in-azure-databricks 
Thanks
Lino

**Comment by crrodger** [comment]
Cheers thank you.

I ran out of time before the workshop to try it. One of the attendees however did get all the way through the workshop and deployed the application using a garbage key, and that seemed to work.

I am delivering the workshop again next week and will try this to retrieve keys and apply in the Azure app deployment.


Craig Rodger
Mobile: +61 406 176 831

**Comment by mathieu-benoit** [comment]
Hi @mrfalafel, thanks for your blog post. I think for this lab we need more clarification and some updates:

1. Either remove the notion of the ML API Key which is not anymore the case with AML now by default when deploying with ACI 
2. Or adding your recommendation of `auth_enabled=True` in `deploy_configuration` of Notebook 3.

Thoughts?
