### ISSUE TITLE
Screen shot differences between portal and guide

### ISSUE THREAD

**Issue by crrodger** [Microsoft/MCW-Big-data-and-visualization#4]
Not a big one but when I follow the guide there are a few instances where the actual Portal Screen does not match the guide images. Not sure if this is due to location or user differences. 

1\ To add the container to the blob store my Portal does not show "Containers", it shows "Browse Blobs" (see image attached).

![image](https://user-images.githubusercontent.com/40052897/41636001-3b82834e-748f-11e8-860e-66c4abf99f09.png)

2\ When creating the Experimentation Service the screen and instructions say "AI + Cognitive Services" where I am seeing "AI and Machine Learning"

**Comment by joelhulen** [comment]
I've addressed # 1 by adding a note to the setup steps, though I see something different from what you see.

I've updated the screenshot for # 2.
