### ISSUE TITLE
Ex 4 - error while running the Azure Data Factory pipeline (no access to storage account)

### ISSUE THREAD

**Issue by mathieu-benoit** [Microsoft/MCW-Big-data-and-visualization#41]
While running the Azure Data Factory pipeline in Exercise 4 in the Notebook 3 for this cell:
```
dfDelays = spark.read.csv("wasbs://" + containerName + "@" + accountName + ".blob.core.windows.net/FlightsAndWeather/*/*/FlightsAndWeather.csv",
                    schema=data_schema,
                    sep=",",
                    header=True)
```
We got this error:
```
shaded.databricks.org.apache.hadoop.fs.azure.AzureException: shaded.databricks.org.apache.hadoop.fs.azure.AzureException: Container sparkcontainer in account storagex6uezrh5wfar2.blob.core.windows.net not found, and we can&apos;t create it using anoynomous credentials, and no credentials found for them in the configuration.
```

Even if we have properly setup the Azure Blob storage output step. Is there anything missing in this lab to have this working?

Notes:
- I needed to update Notebook 3 by replacing `STORAGE-ACCOUNT-NAME` by my appropriate `accountName` - it's not explicitly mentioned in this lab to do so, we need to update the lab instructions in that regards.
- If I change the default access level policy of my blob storage container to public, it's working, it's a temporary workaround but not an ideal solution.

**Comment by mathieu-benoit** [comment]
I'm curious to know if you see the same issue here @mrfalafel @ZoinerTejada @DawnmarieDesJardins?

**Comment by mrfalafel** [comment]
Hi Mathieu
I don't see the problems mentioned here in this issue.
1- Every MCW that uses Databricks uses "STORAGE-ACCOUNT-NAME" as a placeholder for users to enter their own storage name and it says so in the document.
2- The direction for creating "sparkcontainer" is correct with the correct access level policy and it should not be set to public as you mentioned.

I have reviewed this and asked other members of the team to confirm as well and none of us see the issue.
Thanks
-Lino

**Comment by mathieu-benoit** [comment]
Oh ok interesting @mrfalafel, I asked the team I'm working with to see if I'm the only one getting that. Will keep you posted. Thanks.

**Comment by mathieu-benoit** [comment]
@mrfalafel, I just got the confirmation by 2 colleagues of mine who are able to reproduce this issue too.

**Comment by mathieu-benoit** [comment]
And FYI, my remark about "STORAGE-ACCOUNT-NAME" is that's not indicated to change it, but we need to.
On that section: https://github.com/Microsoft/MCW-Big-data-and-visualization/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Big%20data%20and%20visualization.md#task-1-create-azure-databricks-linked-service, it's just saying: 
```
14. Switch back to Azure Databricks. Select Workspace in the menu. Open notebook 04 Deploy for Batch Scoring. Examine the content but don't run any of the cells yet.
```

**Comment by kylebunting** [comment]
@mathieu-benoit, after looking into this I believe the issue is that the connection information for the storage account hasn't been added to the Spark Config of the Databricks cluster. The step for this in included in the Before-the-hands-on-lab document (Task 4, Step 5).

**Spark Config**: Edit the Spark Config by entering the connection information for your Azure Storage account that you copied earlier in Task 5. This will allow your cluster to access the lab files. Enter the following:

        `spark.hadoop.fs.azure.account.key.<STORAGE_ACCOUNT_NAME>.blob.core.windows.net <ACCESS_KEY>`, where <STORAGE_ACCOUNT_NAME> is your Azure Storage account name, and <ACCESS_KEY> is your storage access key.

    **Example:** `spark.hadoop.fs.azure.account.key.bigdatalabstore.blob.core.windows.net HD+91Y77b+TezEu1lh9QXXU2Va6Cjg9bu0RRpb/KtBj8lWQa6jwyA0OGTDmSNVFr8iSlkytIFONEHLdl67Fgxg==`

I understand you were working in a hosted environment, so this is something to check. You should be able to stop the cluster, update the config and restart the cluster to get past this issue.

**Comment by mathieu-benoit** [comment]
Thanks @kylebunting! I could close this issue now since the issue was part of the setup.
Note: PR #47 had been merged too.
