### ISSUE TITLE
Shortcut for running notebook cells

### ISSUE THREAD

**Issue by wsteen** [Microsoft/MCW-Big-data-and-visualization#45]
The shortcut for running notebook cells as mentioned in the HOL step-by-step guide should be Ctrl+Enter instead of Ctrl+Shift.

https://docs.databricks.com/user-guide/notebooks/notebook-use.html

**Comment by DawnmarieDesJardins** [comment]
@ZoinerTejada @mrfalafel 
Hello gentlemen!
Is this a quick fix that can be done before the update in May?
Thanks, Dawnmarie

**Comment by mrfalafel** [comment]
Fixed and committed
