### ISSUE TITLE
Download link is broken in HTML lab guide in Exercise1 Task 2

### ISSUE THREAD

**Issue by Abhishekpathania01** [Microsoft/MCW-Big-data-and-visualization#48]
Exercise 1 Task 2: Open Azure Databricks and complete lab nitebook
Step 1. Download: BigDatavVis.dbc , in HTML guide this link is broken. Got blob not found error.

Could anyone please look into this and fix ASAP, we have a workshop scheduled tomorrow we needed this to be fixed ASAP.

Thanks,
Abhishek Pathania

**Comment by kylebunting** [comment]
@Abhishekpathania01, the missing file has been added to the blob storage account. I have verified that the link now works. Please confirm this is working for you, and I'll close the issue.

**Comment by Abhishekpathania01** [comment]
@kylebunting , Yes the link is working now, Thanks for your quick help and support.
