### ISSUE TITLE
Explicitly fail when someone doesn't enter their subsrciption ID and/or storage account name

### ISSUE THREAD

**Issue by syed** [microsoft/MCW-Big-data-and-visualization#50]
We have found that in Notebook 3 and 4 there are places where participants need to change the subscription ID and storage-account name. This is not called out very clearly. Can we explicitly fail when someone doesn't enter/replace the subscription ID and other required variables

**Comment by DawnmarieDesJardins** [comment]
Closing issue, addressed in June 2019 update.
