### ISSUE TITLE
Instruction to install the PyPi librairie – azureml.core

### ISSUE THREAD

**Issue by mathieu-benoit** [microsoft/MCW-Big-data-and-visualization#51]
Instruction to install the PyPi librairie – azureml.core needs to be documented otherwise the first cell of Notebook 3 will fail.

**Comment by mrfalafel** [comment]
The instructions to install the PyPi libraries are in the previous cell #2 explaining the 3 steps needed to CreateLibrary to include PyPi in the cluster.
![image](https://user-images.githubusercontent.com/1494257/55350684-a4495480-548a-11e9-9e28-22a627043bd7.png)

**Comment by mrfalafel** [comment]
Ok I understand @mathieu-benoit 
I will notify the person scheduled to update this next update, probably @joelhulen to add more instructions.

**Comment by lastcoolnameleft** [comment]
I agree that the directions are not clear.  And either due to the lack of clarity or inaccuracy, I hit an error.  I tried to install it by going to Clusters -> lab (my cluster) -> Libraries -> Install New and then added: `azureml-sdk[databricks]`.

I then ran:
```
import azureml.core
azureml.core.VERSION
```

And got the following error:
```
/databricks/python/lib/python3.5/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Out[2]: '1.0.33'
```

Any thoughts?

**Comment by lastcoolnameleft** [comment]
It appears that if remove that library, reboot the cluster and use the instructions from here, it works. 
 https://github.com/snowstormlife/MCW-Big-data-and-visualization/commit/e90186aac3f4730c8603c7e587ff61567c68e472

That said, how/when can this be merged into this repo's master?

**Comment by DawnmarieDesJardins** [comment]
Closing issue, addressed in June 2019 update.
