### ISSUE TITLE
Issue in Exercise 4 Task 2: Trigger workflow is failing.

### ISSUE THREAD

**Issue by Abhishekpathania01** [Microsoft/MCW-Big-data-and-visualization#52]
In [Exercise 4 Task 2: Trigger Workflow](https://github.com/Microsoft/MCW-Big-data-and-visualization/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Big%20data%20and%20visualization.md#task-2-trigger-workflow) I tried out the lab and found, Trigger is failing with error message: Activity BatchScore failed: Databricks execution failed with error message: . Run page url: https://eastus2.azuredatabricks.net/?o=2487023948884853#job/1/run/1. This URL is pointing to Exercise 4 of Notebook, but according to lab guide we don't need to run this notebook here.

Can someone please look into this on urgent bases. Thanks
Abhishek Pathania

**Comment by DawnmarieDesJardins** [comment]
@kylebunting @joelhulen @ZoinerTejada 
Hello gentlemen, can you please take a look at this one - Spectra advises there is a workshop delivery on 4/4.

**Comment by ZoinerTejada** [comment]
We are looking at this.
