### ISSUE TITLE
Ex.1: Task.2- 3rd Notebook cmd10 is failing

### ISSUE THREAD

**Issue by SeeratArora** [microsoft/MCW-Big-data-and-visualization#56]
Ex.1: Task.2.Step.6.- 3rd Notebook command 10 is giving error: Unable to create the workspace.

![bigdata](https://user-images.githubusercontent.com/50323628/58697950-ef62e380-83b7-11e9-90a6-6d39dc788e9b.png)

**Comment by DawnmarieDesJardins** [comment]
@joelhulen @timahenning 
Hi Joel,
Please review & advise.
Thanks, Dawnmarie

**Comment by joelhulen** [comment]
I'll be working on this and the other issues this week. Please stay tuned.

**Comment by SeeratArora** [comment]
Can you please check on this ASAP, we have a workshop scheduled after 3 days.

**Comment by joelhulen** [comment]
@SeeratArora I just got everything up and running and was able to successfully run this notebook.

Could you please check the following for me?

1. What is the output of `cmd 4` (the Azure ML SDK version)? It should be 1.0.41
2. Please double-check the values you have entered in `cmd 7`. I noticed that these values were already filled out in the imported notebook, and they should have been cleared. Your screenshot shows you are using "lino-ml-workspace" as the workspace name, which was already entered. Please make sure you have your Azure subscription entered, your lab Resource Group name, and a valid region (westus2, eastus2, eastus, westcentralus, southeastasia, australiaeast, or westeurope)

Can you please verify and let me know?

**Comment by SeeratArora** [comment]
@joelhulen  I checked the following points:

1. Output for cmd 4 is 1.0.41
2. In cmd 7 I have checked the values, subscription id and resource group name with a valid region. The command is working fine today. 
I performed it in the same way today as I did it in last attempts where I was getting the error but today it is working well.

Also we see the default path for ML in Notebook 3 is again changed to ‘aml_config’ but it should be .azureml (it’ll need to be changed in cmd 13, 15, 17, 26 Notebook 3).

![bigdata1](https://user-images.githubusercontent.com/50323628/58870088-1d5c6680-86dd-11e9-8c5b-b9dacdaa1a3e.png)

Please check this.

**Comment by joelhulen** [comment]
I'm glad it's working now.

Regarding the ML path, you must be using an older version of the notebooks. I just imported them from the site and the paths are correct:

![image](https://user-images.githubusercontent.com/5950304/58880680-7d83e600-86a6-11e9-8aaf-fa17b9b080d6.png)

As a side note, I'm working on updating this lab and have made a lot of improvements to the layout of the notebooks and lab instructions. Unfortunately, those won't be available for some time. But it sounds like your issues should be resolved for now.

**Comment by Abhishekpathania01** [comment]
@joelhulen I also got the same error In Notebook 3 the one which was earlier reported by @SeeratArora 
![image](https://user-images.githubusercontent.com/38715522/59706369-f8f4a400-921d-11e9-8516-35844850214b.png)

Can you please check on this? I can provide you environment to look into this issue, if needed. 
We noticed when @SeeratArora tested it again it worked fine.  Can we find the root cause why it is not working all the time. 

For meantime, I'll try to do the lab again and will see if it works.

Thank you!

**Comment by joelhulen** [comment]
@Abhishekpathania01 I suspect you are encountering the same issue as @SeeratArora. It also looks like you are using the old version of the notebook, based on your output.

I submitted a PR two weeks ago that updated the notebook and lab instructions. Please see the latest version in my fork until the PR gets merged: https://github.com/joelhulen/MCW-Big-data-and-visualization

**Comment by Abhishekpathania01** [comment]
@joelhulen I am using the link as per lab guide "https://github.com/microsoft/MCW-Big-data-and-visualization/blob/master/Hands-on%20lab/lab-files/BigDataVis.dbc" to download / import the Notebook. 

If this is the case so I am also suspecting how did it work for @SeeratArora  when she tested it second time? As we are using the same Notebook link mentioned in the Lab Guide.

Please suggest

**Comment by joelhulen** [comment]
@Abhishekpathania01 I believe your issue may be the same in that the notebook version is old. Could you please try the new notebook version? https://github.com/joelhulen/MCW-Big-data-and-visualization/blob/master/Hands-on%20lab/lab-files/BigDataVis.dbc

**Comment by Abhishekpathania01** [comment]
Thanks @joelhulen I just tried out the Notebook you provided to me and did not find any issues. Also can we have any idea on long it'll take to get PR merged so all attendees can have the latest Notebooks. 

Thanks!!

**Comment by joelhulen** [comment]
Glad it worked. @DawnmarieDesJardins, what is the deadline for SME review for this update? Once that's done we can merge the PR so attendees can use the latest and greatest.

I suspect it should be this week.

**Comment by DawnmarieDesJardins** [comment]
@Abhishekpathania01 @joelhulen 
Hi gents! SME review closed EOD 6/18/19.  Joel, I just sent you the green light to finalize.  Assign the PR to me when it's ready for QC/merge and give me approx. 48 hours to complete.
Thanks, Dawnmarie

**Comment by SanjayWoorvakonda** [comment]
@DawnmarieDesJardins  Thanks a lot!
@joelhulen I think the PR is mergerd and Lab guide is updated now. 
I have one doubt:
1. For databricks cluster, we have to use Databricks Runtime Version: 5.3 (includes Apache Spark 2.4.0, Scala 2.11) as per the lab guide, but in the portal we don't have same runtime version. 

We've following available (5.3) versions in Azure portal:
![image](https://user-images.githubusercontent.com/44019116/59976723-1773ea00-95e6-11e9-8d97-686e903f6562.png)
2. Also can you please confirm if the changes are also taken care in the HTML lab guide as well?

Thanks
Abhishek

**Comment by Abhishekpathania01** [comment]
@DawnmarieDesJardins  Thanks a lot!
@joelhulen I think the PR is mergerd and Lab guide is updated now. 
I have one doubt:
1. For databricks cluster, we have to use Databricks Runtime Version: 5.3 (includes Apache Spark 2.4.0, Scala 2.11) as per the lab guide, but in the portal we don't have same runtime version. 

We've following available (5.3) versions in Azure portal:
![image](https://user-images.githubusercontent.com/44019116/59976723-1773ea00-95e6-11e9-8d97-686e903f6562.png)
2. Also can you please confirm if the changes are also taken care in the HTML lab guide as well?

Thanks
Abhishek

**Comment by Abhishekpathania01** [comment]
@joelhulen I just went through the Notebooks downloaded from HTML Lab guide, and it seems that aml path needs to be correct there. Also can you please confirm all issues has been taken care in HTML lab guide,because we'll need to provides HTML links to users "https://cloudworkshop.blob.core.windows.net/big-data-vizualization/Hands-on%20lab/HOL%20step-by-step%20-%20Big%20data%20and%20visualization.html"

**Comment by Abhishekpathania01** [comment]
Hi @joelhulen I found one more issue, when checking the Azure aml version in the Exercise 3, when running the command : import azureml.core
azureml.core.VERSION , it is showing the below error: 
![image](https://user-images.githubusercontent.com/38715522/60014583-f28f7d80-969e-11e9-83c4-8b0358fbe3ac.png)


and when running this same command second time, it is working fine. Please check on this as well. 

Thanks!!!

**Comment by DawnmarieDesJardins** [comment]
@Abhishekpathania01 
Hi there!  HTML was updated after I merged the update to master.  Any time there's an update, I run the HTML script.  Thanks, Dawnmarie

**Comment by Abhishekpathania01** [comment]
> @DawnmarieDesJardins Thanks a lot!
> @joelhulen I think the PR is mergerd and Lab guide is updated now.
> I have one doubt:
> 
> 1. For databricks cluster, we have to use Databricks Runtime Version: 5.3 (includes Apache Spark 2.4.0, Scala 2.11) as per the lab guide, but in the portal we don't have same runtime version.
> 
> We've following available (5.3) versions in Azure portal:
> ![image](https://user-images.githubusercontent.com/44019116/59976723-1773ea00-95e6-11e9-8d97-686e903f6562.png)
> 2. Also can you please confirm if the changes are also taken care in the HTML lab guide as well?
> 
> Thanks
> Abhishek

Any update on this??

**Comment by Abhishekpathania01** [comment]
> @Abhishekpathania01
> Hi there! HTML was updated after I merged the update to master. Any time there's an update, I run the HTML script. Thanks, Dawnmarie

Thanks, but I checked the Notebooks from both Lab guide and found both are different (Notebooks in HTML lab guide are atill need to be updated

**Comment by DawnmarieDesJardins** [comment]
@Abhishekpathania01 
Hello, I'm running the HTML script again, just in case.  Please give it a few minutes, then clear your cache and review the file again.
Thanks, Dawnmarie
