### ISSUE TITLE
Databricks Notebook Exercise 5 01 Deploy for Batch Scoring fails with Py4JJavaError error

### ISSUE THREAD

**Issue by striple66** [microsoft/MCW-Big-data-and-visualization#59]
Hi, when I try to run the Databricks Notebook "01 Deploy for Batch Scoring" in Exercise 5, the Cmd 15 fails with a Py4JJavaError error:

`
(1) Spark Jobs
Job 293 View(Stages: 0/0, 1 skipped)

org.apache.spark.SparkException: Job aborted.
---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<command-1180400324146953> in <module>()
----> 1 prediction.write.mode("overwrite").saveAsTable("scoredflights")

/databricks/spark/python/pyspark/sql/readwriter.py in saveAsTable(self, name, format, mode, partitionBy, **options)
    773         if format is not None:
    774             self.format(format)
--> 775         self._jwrite.saveAsTable(name)
    776 
    777     @since(1.4)

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):`

**Comment by DawnmarieDesJardins** [comment]
@timahenning 
Please review/advise.

**Comment by joelhulen** [comment]
@striple66 I have fully tested the lab up to this point and I am not seeing the error you listed above. Did you run this notebook from Azure Data Factory, or did you attempt to run it directly? Also, I will ask the same question here as I asked in your other open issue: Did you download the notebooks from this repo directly in Databricks, as instructed? The link in the instructions is relative to the HoL document. I wonder if perhaps you are following steps from a forked repo or some other location?

**Comment by striple66** [comment]
Hi Joel,
Thank you so much for looking after my issues. I am Pretty sure I used the download links provided in the HOL Step by step guide in the MCW material from Github. Let me check tomorrow once again – I will download the BigDataVis.dbc again. Please find attached the file I used to Import into Databricks.

I tried to execute the Notebook Exercise 5 directly from Databricks – just wanted to check if it runs fine in Databricks first before I run the Pipeline. 

Please excure but I do not get your statement: „The link in the instructions is relative to the HoL document.” What does this mean? 😊

Here in Germany it is 11:00 PM now- I will re-run everything tomorrow and let you know.

Thanks and best regards

Ralf


Gesendet von Mail für Windows 10

Von: Joel Hulen
Gesendet: Monday, 5 August 2019 22:25
An: microsoft/MCW-Big-data-and-visualization
Cc: striple66; Mention
Betreff: Re: [microsoft/MCW-Big-data-and-visualization] Databricks NotebookExercise 5 01 Deploy for Batch Scoring fails with Py4JJavaError error (#59)

@striple66 I have fully tested the lab up to this point and I am not seeing the error you listed above. Did you run this notebook from Azure Data Factory, or did you attempt to run it directly? Also, I will ask the same question here as I asked in your other open issue: Did you download the notebooks from this repo directly in Databricks, as instructed? The link in the instructions is relative to the HoL document. I wonder if perhaps you are following steps from a forked repo or some other location?

**Comment by joelhulen** [comment]
Closing due to this being an issue with the user's environment.
