### ISSUE TITLE
Fake name issue

### ISSUE THREAD

**Issue by emilysaeli** [Microsoft/MCW-Big-data-and-visualization#6]
Adventure Works Travel is not on the list of approved fictitious names. Adventure Works Cycles is, but it doesn't make sense to have a cycle company in the example without a bunch of changes to the travel company example.

**Comment by joelhulen** [comment]
I will rename to Margie's Travel, per the list of approved fictitious company names.

**Comment by joelhulen** [comment]
Renamed in all files, including web project and Databricks notebooks. Also replaced the AWT logo with a new Margie's Travel logo.
