### ISSUE TITLE
Exercise 8: Deploy intelligent web app - Issue in the GUI ( Using Existing RG)

### ISSUE THREAD

**Issue by Abhishekpathania01** [microsoft/MCW-Big-data-and-visualization#64]
Hi @joelhulen 

In **Exercise 8: Deploy intelligent web app** [Task 2 Deploy web app from GitHub](https://github.com/microsoft/MCW-Big-data-and-visualization/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Big%20data%20and%20visualization.md#task-2-deploy-web-app-from-github) When we click on provided URL: https://github.com/Microsoft/MCW-Big-data-and-visualization/blob/master/Hands-on%20lab/lab-files/BigDataTravel/README.md to deploy the web, it re-directs to the Azure portal and opens the GUI as show in below image:
![image](https://user-images.githubusercontent.com/38715522/66027924-9350cd00-e519-11e9-9451-d1b5cd705458.png)

In this GUI, we have two options for Resource Group - 1. We can select Existing Resource Group 2. We can create a new Resource Group. 

Issue: When we're selecting Existing Resource Group even after that it asks for the permissions to create a new Reaource Group. 

As, we're using shared subscription pool for this workshop we can't give subscription level permission to users to create new Resource Group. We're proving them a pre-created Resource Group and it works for the lab fine. Only we're having issue while deploying this web app - as it is asking subscription level permissions to create a new resource group. 

Could you please take a look and see if this can be fixed ( selecting existing Resource Group can work as expected) ?

I can provide you one lab environment, if needed. 

Thanks in Advance!
Abhishek Pathania

**Comment by joelhulen** [comment]
@Abhishekpathania01 , I've updated the web project so it successfully deploys and builds from the GitHub repo (see PR #65). I am able to select an existing Resource Group and have it deploy there. Perhaps I cannot reproduce without the account restriction. Can you please try again with the latest changes?

**Comment by Abhishekpathania01** [comment]
Thank you! @joelhulen  I'll test it out soon and will let you know the status on it.

Thanks again for your quick help and support.

**Comment by Abhishekpathania01** [comment]
Hi @joelhulen I just tried out the same step to deploy web app but I am still facing same issue. Earlier also I was able to select the existing Resource Group but issue was related to permissions. After selecting existing Resource Group it says: **AuthorizationFailed: The client 'odl_user_xxxxx@cloudlabsxxxxxx.onmicrosoft.com' with object id 'xxxxxxxx-f83f-4500-a30e-d93b75c9f71e' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/write' over scope '/subscriptions/xxxxx-1d07-4890-83c6-xxxxxxxxx/resourcegroups/5cd0d53b-e6a1-xxxx-xxxxxxx' or the scope is invalid. If access was recently granted, please refresh your credentials**

![image](https://user-images.githubusercontent.com/38715522/66166077-e038be80-e653-11e9-8cd9-a1f2126b6330.png)

User is having **Contributor** on Resource Group and user can deploy the web app. Could you please check it and see if it can be fixed? For creating New Reaource Group we'll need to give subscription level permission which is not possible on Shared subscription pool. 

Thanks!!

**Comment by joelhulen** [comment]
@Abhishekpathania01 Unfortunately, there is nothing I can do about this error. We are using a simple ARM template for the deployment (https://github.com/microsoft/MCW-Big-data-and-visualization/blob/master/Hands-on%20lab/lab-files/BigDataTravel/azuredeploy.json), and the deploy.azure.com site is owned and maintained by Microsoft. It takes the ARM template, creates a nice user interface to input the values, then configures automated deployment to a new Web App by creating a deployment environment within the Web App, then setting up the Kudu automated build against the GitHub repo.

There are two other options if this is a show stopper:

1. We make Visual Studio a prerequisite, have students download the lab files, then deploy from within VS.
2. Have students fork this repo, create a new Web App in the portal, then create a deployment environment in their Web App by pointing to their forked repository and selecting the Kudu build.

Both of these options have consequences. Can you think of any other workaround that won't involve several more steps that have to be documented or undesired pre-requisites?

**Comment by Abhishekpathania01** [comment]
Thanks @joelhulen I am agree with the #1 option: Make a VS as a pre-requisite, have studrnt files then deploy from within VS. If you can update the pre-requisite like this, it'd be great. 

Another option: If we can replace that URL with another URL which will re-direct to Azure portal ( load the template to deploy the web app - instead of opening up GUI(existing one). example: https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAzure%2Fazure-quickstart-templates%2Fmaster%2F101-1vm-2nics-2subnets-1vnet%2Fazuredeploy.json 

Please see if either of these works. 

Thanks, 
Abhishek

**Comment by DawnmarieDesJardins** [comment]
@joelhulen - your advise for next steps?  Thanks

**Comment by joelhulen** [comment]
I added a paragraph at the top of Exercise 8 explaining how attendees can use a workaround to deploy the web app in hosted environments that lock down resource group creation.

**Comment by Abhishekpathania01** [comment]
Thank You! @joelhulen I hope this will work without running in to any issues. Can you please add some pre-requisites steps for this? like how they will get this web app inside Visual Studio.. May be we can download it as student files and show which file they need to open and publish.

Please check if this is possible, it would  be helpful for users. 

Thanks once again,
Abhishek

**Comment by joelhulen** [comment]
It will work without running into any issues. I recently tested it.

I'm wondering how far we need to go. It is marked as an optional exercise, and we cannot accommodate every possible environmental use case. What I can do is add a quick list of cursory steps, and it would be the job of proctors to help guide in those situations.

**Comment by joelhulen** [comment]
@Abhishekpathania01 I've added the additional manual steps in Exercise 8, Task 3 (optional) for all lab attendees who do not have appropriate permissions for the automated deployment to work.
