### ISSUE TITLE
Links and Screen Shots Need Updating

### ISSUE THREAD

**Issue by marktab** [microsoft/MCW-Big-data-and-visualization#69]
With client who would like to complete this lab -- the mismatch of the ever-changing interface needs to be resynchronized, thanks

**Comment by timahenning** [comment]
Thank you for reporting this issue.  Please take a moment to review the help and support guidance.  https://microsoftcloudworkshop.com/  

Having specific lab section references and screenshots will help expedite support. We will review your issue soon.

Tim

**Comment by marktab** [comment]
OK forget it -- we have decided that if we are customer-facing in the future, we will simply fork and fix as needed
