### ISSUE TITLE
Signup option is no more available on Dark Sky API in optional Exercise 8

### ISSUE THREAD

**Issue by akn9050** [microsoft/MCW-Big-data-and-visualization#72]
Optional Exercise 8, can't be performed because new signup's are not possible for Dark Sky API 
Signup option is no more available on Dark Sky API.

**Comment by joelhulen** [comment]
I am going to remove the optional Exercise 8 for now. I suggest that we address the weather API issue in a future update, since changing to a different one will involve significant code changes.

@DawnmarieDesJardins Are you OK with this approach?

**Comment by DawnmarieDesJardins** [comment]
@joelhulen @nderhem 
Hi Joel, 
I agree, let's removed the option exercise for now.  Please create an enhancement issue so we can address re adding the lesson in the next scheduled update.
