### ISSUE TITLE
June 2020 Update Suggestions

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-Big-data-and-visualization#75]

**Comment by joelhulen** [comment]
I suggest the following updates. Please provide feedback:

1. There is not enough in the WDS that covers security. We should add secrets management, especially for managing connection strings to Azure SQL DB, backed by Key Vault.
2. Configure Audit Logs and resource utilization metrics to monitor activity (WDS).
3. Find a new weather API to replace DarkSky and update lab instructions and web application code to use the new API.

**Comment by joelhulen** [comment]
I have submitted a new pull request (#76) for this update. Please review.
