### ISSUE TITLE
Unable to upload FlightDelaysWithAirportCodes.csv file

### ISSUE THREAD

**Issue by madubey** [microsoft/MCW-Big-data-and-visualization#77]
Unable to upload FlightDelaysWithAirportCodes.csv file. This file has some issues.

**Comment by joelhulen** [comment]
Could you please clarify what you mean by issues? We just updated the lab and did not encounter issues uploading the CSV files to Databricks. Also, there is a pending pull request (#76) that includes some changes to the lab. However, nothing changed with the CSV files.

**Comment by DawnmarieDesJardins** [comment]
@madubey 
Hello!  Are you still having trouble with the CSV file?

**Comment by DawnmarieDesJardins** [comment]
Closing issue as no further response.  Please reopen if needed.
