### ISSUE TITLE
Exercise 2: Task 3: Failure in importing BigData.dbc file

### ISSUE THREAD

**Issue by SeeratArora** [microsoft/MCW-Big-data-and-visualization#78]
[Exercise 2: Task 3:](https://github.com/microsoft/MCW-Big-data-and-visualization/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20Big%20data%20and%20visualization.md#task-3-open-azure-databricks-and-complete-lab-notebooks) Step 2: Unable to import the BigData.dbc file by using the URL provided in the Lab Guide. On importing it gave the error saying- Import Failed (image shown below).

![image](https://user-images.githubusercontent.com/50323628/90603234-9b405b00-e218-11ea-9c5c-40105643c348.png)

I tried downloading the BigData.dbc file to my systems and then uploading it to Users Workspace, which worked fine for me. 

Can you please have a look into this?

Thanks,
Seerat Arora

**Comment by joelhulen** [comment]
I just tried importing from the URL and I see the same error. Investigating.

**Comment by SeeratArora** [comment]
Hi @joelhulen 
Do we updates on this?
