### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by mreherefortea** [microsoft/MCW-Big-data-and-visualization#86]
Hello Team:

A few things have changed since this was originally authored. In the before the hands on lab, Task 2, Access Tiers is no longer on the default page but under the "Advanced" page. 

Same section, Task 4:  it is now called Data Factories instead of Data Factory. 

In Ex 1, Task 2 Step 5, runtime version 6.5 was not available but 6.4 worked. 
In Ex 8, Task 3, Step 7 the screenshots are pretty outdated here and could use a refresher.  

Thank you for your time.

**Comment by DawnmarieDesJardins** [comment]
@mreherefortea 
Thank you!  We are in the process of reviewing workshops for Q3 updates, this is really helpful.  Marking this issue as an enhancement for review.
