### ISSUE TITLE
Instructions need to be update in exercise 1 and exercise 3/ Task 3 

### ISSUE THREAD

**Issue by Divyasri199** [microsoft/MCW-Big-data-and-visualization#92]
In exercise 3/ task 3 after step 14 didn’t mention anything about the backup file
![image](https://user-images.githubusercontent.com/83349577/119999161-0fe9c680-bfef-11eb-8447-602205eae0d7.png)
FYI I have tested the lab by skipping the backup file part and I am able to complete the lab without any issues.
Please update the required.

In Exercise 1/ Task 2/ Step 5, In the instances provided for the creating New Cluster Form, the version of the runtime is not available in VM.  
The Run time version mentioned in the lab guide was Runtime: 6.4 (Scala 2.11, Spark 2.4.5)
The Run time version available in VM was : Runtime: 6.4 Extended Support (Scala 2.11, Spark 2.4.5)
![image](https://user-images.githubusercontent.com/83349577/120000447-728f9200-bff0-11eb-9b8a-50198e41277b.png)

**Comment by saimachi** [comment]
Thank you for bringing this to our attention, @Divyasri199. I have addressed this in PR #93.
