### ISSUE TITLE
ScreenShots and Intructions needs to be update.

### ISSUE THREAD

**Issue by Divyasri199** [microsoft/MCW-Big-data-and-visualization#94]
In Exercise-4/task-1/step-2-> It is given in the lab guide  to mention the task name and task description, but there are no options available for that in VM.
![image](https://user-images.githubusercontent.com/83349577/123741564-eb239000-d8c7-11eb-8f26-3d7b9aa31bae.png)

In the exercise-4/ task-1/step-8-> it is mentioned to select “NEXT” on the source data page before moving to the next step
But we have to perform the next step in the same page.

![image](https://user-images.githubusercontent.com/83349577/123741725-258d2d00-d8c8-11eb-88dd-c265b581ebd7.png)

In exercise-4/ task-1/ step-10-> In guide it is mentioned option as auto detect, but in Virtual Machine it is default.
And it has to be mentioned in the guide to click on preview data to see the table.
![image](https://user-images.githubusercontent.com/83349577/123741849-6127f700-d8c8-11eb-8557-4c32bc65c614.png)

In exercise-4/ task-1/ step-15-> it is mentioned to select “NEXT” on the source data page before moving to the next step
But we have to perform the next step in the same page, should not click on next until we mention folder path in the same page.

![image](https://user-images.githubusercontent.com/83349577/123741957-8e74a500-d8c8-11eb-915b-87d3e10b2a4f.png)

In Exercise-1/task-2/step4-> The ScreenShot has to be replaced
![image](https://user-images.githubusercontent.com/83349577/123743221-86b60000-d8ca-11eb-8244-955e5bb7ae7f.png)
![image](https://user-images.githubusercontent.com/83349577/123743244-8ddd0e00-d8ca-11eb-9817-fce4618b5b68.png)

**Comment by saimachi** [comment]
Hi @Divyasri199,

Thanks for bringing this issue to our attention. I have updated all the images on my [fork](https://github.com/saimachi/MCW-Big-data-and-visualization/tree/issue-94). We will merge this into the lab soon.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved with merge of PR #95
