### ISSUE TITLE
Deploy as Web service notebook cell error

### ISSUE THREAD

**Issue by GautamRaviKumar** [microsoft/MCW-Big-data-and-visualization#97]
Trying to deploy to the Azure Container Instance gets me an error in this part of the code:

service_name = "sparkmlservicedb001"

from azureml.core.webservice import AciWebservice, Webservice
from azureml.exceptions import WebserviceException
try:
    # if you want to get existing service below is the command
    # since aci name needs to be unique in subscription deleting existing aci if any
    # we use aci_service_name to create azure aci
    service1 = Webservice(ws, name=service_name)
    if service1:
        service1.delete()
except WebserviceException as e:
    print()

service = Model.deploy(ws, service_name, [mymodel], inference_config, aci_config)
service.wait_for_deployment(show_output=True)     <------------------------------------ERROR HERE
print(service.state)

Here is the error:

FailedService deployment polling reached non-successful terminal state, current service state: Transitioning
Operation ID: c0b9af65-b3d3-4665-bd55-6966b02754f5
More information can be found here: https://amlbigdastorage7dfe13aed.blob.core.windows.net/azureml/ImageLogs/c0b9af65-b3d3-4665-bd55-6966b02754f5/build.log?sv=2019-02-02&sr=b&sig=AcgAv1qLhCtopz3X2bVUxFG%2FUmlZXfKdMJgkB1L1ue8%3D&st=2021-08-04T06%3A28%3A41Z&se=2021-08-04T14%3A33%3A41Z&sp=r
Error:
{
  "code": "AciDeploymentFailed",
  "statusCode": 401,
  "message": "Failed to fetch details for Environment with Name: AzureML-PySpark-MmlSpark-0.15 Version: 45 Reason: Authentication failed for Container Registry: hub.docker.com..",
  "details": []
}

**Comment by feaselkl** [comment]
I've confirmed that I receive the same error when going through the hands-on lab steps.  It looks like the cause of this is that the Azure Machine Learning team has removed AzureML-PySpark-MmlSpark-0.15 from their list of available environments and there is no ready alternative among the available alternatives.

This is the same issue as #96 and we will need to design an alternative or change the lab.

**Comment by timahenning** [comment]
There will be a lab update fix in 2 to 3 months/Q2.  You will have to skip this portion of lab for now.
