### ISSUE TITLE
Enhancements for Q2 Update

### ISSUE THREAD

**Issue by feaselkl** [microsoft/MCW-Big-data-and-visualization#99]
Here are recommended changes for the Q2 update of this MCW.

* Create an ARM template for the before-the-lab work in setting up Azure Data Factory, Azure Blob Storage, Databricks, and the Integration Runtime VM.  The VM should run Windows Server Datacenter 2019.
* Ensure that images and explanations are up to date with Azure services.  Replace images containing text blocks (e.g., "use 6.4 Extended" for Databricks) with up-to-date instructions.
* Update notebooks to support the current Databricks runtime.  This will solve #79 
* Exercise 2:  use Databricks for model deployment instead of Azure Machine Learning.  This will also solve #96 and #97
* For exercise 2 lab 2, change the process from saving a model locally to creating an experiment and saving the model as an artifact of the experiment.
* For exercise 2 lab 3, perform model deployment and enable a REST endpoint.
* Change the application code in exercise 8 to call the Databricks REST endpoint instead of the Azure Machine Learning REST endpoint.  Update the code to support any differences in call output.

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #100
